<?php
namespace common\models;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;
use yii\helpers\Url;
use Yii;
use common\models\base\Categories;
use yii\web\UploadedFile;

class Products extends \common\models\base\Products {
    public $file_image;

    public $file_360;

    public $qr;



    public static function getCategoriesName() {
        $categories = \common\models\base\Categories::find()->all();
        $arr_cate = [];
        foreach($categories as $cate) {
            $arr_cate[$cate->id_category] = $cate->name_category;
        }
        return $arr_cate;
    }

    public function createQR() {
        var_dump($this->id_products);
        $writer = new PngWriter();
//        $url =  Url::to([Yii::$app->homeUrl.'/products/view', 'id_products' => $this->id_category]);
        $baseUrl = $_SERVER['HTTP_HOST'] .  Yii::getAlias('@web');
        $parentDirectory = dirname(dirname($baseUrl)) . '/';
        $url = $parentDirectory . 'anh360/products/detail?id_products='.$this->id_products;

        $qr = QrCode::create($url);

        $res = $writer->write($qr);
        $path = '../../qr/'.$this->name_products.time().'.png';
        $res -> saveToFile($path);
        $this->setAttribute('qr_code', $path);
        return $path;
    }



    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_at = time();
            $this->created_by = Yii::$app->user->identity->username;
        } else {
            $this->updated_at = time();
            $this->updated_by = Yii::$app->user->identity->username;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            if (!empty($this->qr)) {
                $qrImg = Yii::getAlias('@image_360/qr/') . $this->qr->name;
                $this->qr->saveAs($qrImg);
            } else {
                $qrPath = $this->createQR();
                $this->qr_code = basename($qrPath);
                $this->setAttribute('qr_code', $this->qr_code);
                $this->qr = UploadedFile::getInstance($this, 'qr');
            }
            $this->save(false);
        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}