<?php
namespace common\models;

use common\models\base\Users;
use PhpParser\Node\Stmt\Expression;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;


class User extends \common\models\base\Users implements IdentityInterface 
{

    public $auth_key;
    public $password_reset_token;
    public static function findIdentity($id)
    {
        return static::findOne(['id_user' => $id]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }


    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
     }
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }


    public function setPassword($password)
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }


    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new token for email verification
     */
    // public function generateEmailVerificationToken()
    // {
    //     $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    // }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    public function beforeSave($insert) {
        if ($insert) {
            $this -> setPassword($this->password);
            $this->generateAuthKey();
            $this->generatePasswordResetToken();
            $this->created_at = time();
            if (Users::find()->all() ==null) {
                $this->created_by = $this->username;
            } else {
                $this->created_by = Yii::$app->user->identity->username;
            }
        } else {
            $old_user = User::findOne($this->id_user);
            if($this->password != $old_user->password) {
                $this -> setPassword($this->password);
                $this->generateAuthKey();
                $this->generatePasswordResetToken();
            }
            $this->updated_at = time();
            $this->updated_by = Yii::$app->user->identity->username;
        }
        return parent::beforeSave(($insert));
    }

    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            $profile = new Profile();
            $profile->id_user = $this->id_user;

            $profile->avatar = 'no-avatar.jpg';
            $profile->created_at = time();
            if (Profile::find()->all() ==null) {
                $this->created_by = $this->username;
            } else {
                $this->created_by = Yii::$app->user->identity->username;
            }
            $profile->save(false);
        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}

