<?php
namespace frontend\widgets;
use yii\base\Widget;
use common\models\Categories;
class categoryWidget extends Widget {
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $cate = Categories::find()->where(['status'=>'Hiện'])->all();
        return $this->render('categoryWidget', [
            'cate' => $cate
        ]);
    }
}