<?php
namespace frontend\widgets;
use yii\base\Widget;
use common\models\Products;


class contentHomeWidget extends Widget {
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $products = Products::find()
            ->innerJoin('categories', 'categories.id_category = products.id_category')
            ->where(['products.status' => 'Hoạt động', 'categories.status' => 'Hiện'])
            ->orderBy(['id_products'=>SORT_DESC])
            ->limit(8)
            ->all();
        return $this->render('contentHomeWidget', [
            'products' => $products
        ]);
    }
}