<?php
namespace frontend\widgets;
use yii\base\Widget;

class headerWidget extends Widget {
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('headerWidget');
    }
}