<?php
namespace frontend\widgets;
use yii\base\Widget;
use frontend\models\Products;
use yii\db\Query;

class popular extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $query = new Query();
        $query->select(['products.*', 'view.view_count']) // Đặt trường view.view_count sau products.*
            ->from('products')
            ->innerJoin('categories', 'categories.id_category = products.id_category')
            ->innerJoin('view', 'view.id_products = products.id_products')
            ->where(['products.status' => 'Hoạt động', 'categories.status' => 'Hiện'])
            ->orderBy(['view.view_count' => SORT_DESC])
            ->limit(3);

        $products = $query->all();
        return $this->render('popular',
        [
            'products'=>$products
        ]);
    }
}