<?php
namespace frontend\widgets;
use yii\base\Widget;
use frontend\models\Products;
class recommendedWidget extends Widget {
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $products = new Products();
        return $this->render('recommendedWidget');
    }
}