<?php
namespace frontend\widgets;
use common\helper\StarProducts;
use yii\base\Widget;
use common\models\Products;
use yii\db\Query;
use common\models\base\Rate;

class scroll extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $products = Products::find()
            ->innerJoin('categories', 'categories.id_category = products.id_category')
            ->where(['products.status' => 'Hoạt động', 'categories.status' => 'Hiện'])
            ->orderBy(['id_products'=>SORT_DESC])
            ->all();

        $starHelper = new StarProducts();
        $averageRatings = $starHelper->getStar($products);


        return $this->render('scroll',
        [
            'products'=>$products,
            'averageRatings'=>$averageRatings
        ]);
    }
}