<?php
namespace frontend\widgets;
use yii\base\Widget;
use frontend\models\Products;
use kartik\form\ActiveForm;
use kartik\autocomplete\Autocomplete;
use yii\helpers\Html;
use Yii;



class searchBarWidget extends Widget {
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('searchBarWidget');
    }
}