<?php
namespace frontend\widgets;

use yii\base\Widget;
use common\models\Categories;

class searchBarWidget extends Widget
{
    public $messsage;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        // $this->$cate = Categories::find()->all();
    }

    public function run()
    {
        return $this->render('searchBarWidget');


        // $cate = Categories::find()->all();  //truy vấn

        // hiển thị
        // return $this->render('categoryWidget', [
        //     'cate' => $cate
        // ]);

        // foreach ($cate as $category) {
        //     echo $category->name_category;
        // }

        // $categories = Categories::find()->all();
        // $dropdownItems = '';
        // foreach ($categories as $category) {
        //     $dropdownItems .= '<a class="dropdown-item" href="#">' . $category->name_category . '</a>';
        // }
        // $html = <<<HTML
        // <div class="dropdown">
        //     <div id="drop-text" class="dropdown-text">
        //         <span id="span" class="every">Everything</span>
        //         <i id="icon" class="arrow-down"></i>
        //     </div>
        //     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        //         $dropdownItems
        //     </div>
        // </div>
        // HTML;
        // return $html;
    }
}