<?php

namespace frontend\widgets;

use common\helper\StarProducts;
use yii\base\Widget;
use common\models\Products;
use yii\data\Pagination;
use yii\db\Query;
use common\models\base\Rate;

class showProducts extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $query = Products::find()
            ->innerJoin('categories', 'categories.id_category = products.id_category')
            ->where(['products.status' => 'Hoạt động', 'categories.status' => 'Hiện'])
            ->orderBy(['id_products' => SORT_DESC]);

        $pagination = new Pagination([
            'defaultPageSize' => 12,
            'totalCount' => $query->count(),
        ]);

        $products = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $starHelper = new StarProducts();
        $averageRatings = $starHelper->getStar($products);

        return $this->render('showProducts',
            [
                'products' => $products,
                'averageRatings' => $averageRatings,
                'pagination' => $pagination
            ]);
    }
}