<?php
namespace frontend\widgets;
use yii\base\Widget;
use yii\db\Query;

class topRateWidget extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $query = new Query();
        $query->select(['products.id_products','products.name_products', 'products.image', 'ROUND(AVG(rate), 1) AS average_rating'])
            ->from('rate')
            ->innerJoin('products', 'rate.id_products = products.id_products')
            ->groupBy('rate.id_products')
            ->orderBy(['average_rating' => SORT_DESC])
            ->limit(10);
        $top10Rate = $query->all();

        return $this->render('topRateWidget', [
            'top10Rate'=>$top10Rate
        ]);
    }
}